[ci skip] Minor build.gradle changes - Experiencing NoClassDefFoundError in coverage testing (stevesaliman/gradle-cobertura-plugin#107)   - May switch to Jacoco